language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.16"
  - "7.10"
  - "8.15"
  - "9.11"
  - "10.15"
  - "11.10"
sudo: false
dist: precise
cache:
  directories:
    - node_modules
before_install:
  - |
    function v () {
      tr '.' '\n' <<< "${1}" \
        | awk '{ printf "%03d", $0 }' \
        | sed 's/^0*//'
    }
  # Configure npm
  - |
    # Skip updating shrinkwrap / lock
    npm config set shrinkwrap false
  # Setup Node.js version-specific dependencies
  - |
    # mocha for testing
    if [[ "$(v "$TRAVIS_NODE_VERSION")" -lt "$(v '0.8')" ]]; then
      # - use 1.x for Node.js < 0.8
      npm install --save-dev mocha@1.21.5
    elif [[ "$(v "$TRAVIS_NODE_VERSION")" -lt "$(v '0.10')" ]]; then
      # - use 2.x for Node.js < 0.10
      npm install --save-dev mocha@2.5.3
    elif [[ "$(v "$TRAVIS_NODE_VERSION")" -lt "$(v '4.0')" ]]; then
      # - use 3.x for Node.js < 4
      npm install --save-dev mocha@3.5.3
    elif [[ "$(v "$TRAVIS_NODE_VERSION")" -lt "$(v '6.0')" ]]; then
      # - use 5.x for Node.js < 6
      npm install --save-dev mocha@5.2.0
    fi
  - |
    # nyc for coverage
    if [[ "$(v "$TRAVIS_NODE_VERSION")" -lt "$(v '6.0')" ]]; then
      # - remove on Node.js < 6
      npm rm --save-dev nyc
    fi
  - |
    # eslint for linting
    if [[ "$(v "$TRAVIS_NODE_VERSION")" -lt "$(v '6.0')" ]]; then
      # - remove on Node.js < 6
      node -pe 'Object.keys(require("./package").devDependencies).join("\n")' | \
        grep -E '^eslint(-|$)' | \
        xargs npm rm --save-dev
    fi
  # Update Node.js modules
  - |
    # Prune & rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi

script:
  - |
    # Run test script, depending on nyc install
    if npm -ps ls nyc | grep -q nyc; then
      npm run-script test-travis
    else
      npm test
    fi
  - |
    # Run linting, depending on eslint install
    if npm -ps ls eslint | grep -q eslint; then
      npm run-script lint
    fi
after_script:
  - |
    # Upload coverage to coveralls, if exists
    if [[ -d .nyc_output ]]; then
      npm install --save-dev coveralls@2
      nyc report --reporter=text-lcov | coveralls
    fi
